# Generated by Django 2.2 on 2020-02-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='rate_count',
            field=models.BigIntegerField(default=0, help_text='点评数量', null=True, verbose_name='点评数量'),
        ),
        migrations.AddField(
            model_name='dish',
            name='rate_score',
            field=models.FloatField(blank=True, help_text='评分', null=True, verbose_name='评分'),
        ),
        migrations.AddField(
            model_name='dish',
            name='sales_count',
            field=models.BigIntegerField(default=0, help_text='销售数量', null=True, verbose_name='销售数量'),
        ),
    ]
