# Generated by Django 2.2 on 2020-02-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0002_auto_20200224_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='dish_image_0',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='dish_image_2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='dish_image_3',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='dish_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='sales_count',
            new_name='sales',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='dish_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='dish_image_1',
        ),
        migrations.AddField(
            model_name='dish',
            name='dish4',
            field=models.ImageField(blank=True, help_text='照片4', null=True, upload_to='dish/', verbose_name='照片4'),
        ),
    ]
