# Generated by Django 2.2 on 2020-02-21 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0002_auto_20200220_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='菜品名称')),
                ('dish_image_0', models.ImageField(blank=True, null=True, upload_to='dish/', verbose_name='主照片')),
                ('dish_image_1', models.ImageField(blank=True, null=True, upload_to='dish/', verbose_name='照片1')),
                ('dish_image_2', models.ImageField(blank=True, null=True, upload_to='dish/', verbose_name='照片2')),
                ('dish_image_3', models.ImageField(blank=True, null=True, upload_to='dish/', verbose_name='照片3')),
                ('dish_desc', models.TextField(blank=True, max_length=2000, null=True, verbose_name='菜品描述')),
                ('dish_price', models.DecimalField(decimal_places=2, default=18.0, max_digits=9, null=True, verbose_name='菜品价格')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否有效')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '菜品',
                'verbose_name_plural': '菜品',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='订单编号')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='订单日期')),
                ('total_marked_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='订单标价')),
                ('total_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='订单折扣')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='订单金额')),
                ('item_count', models.IntegerField(blank=True, null=True, verbose_name='产品数量')),
                ('is_payed', models.BooleanField(default=False, verbose_name='已经支付')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否有效')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='餐馆名称')),
                ('restaurant_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='餐馆企业识别码')),
                ('restaurant_address', models.TextField(blank=True, max_length=2000, null=True, verbose_name='餐馆地址')),
                ('center', models.CharField(blank=True, max_length=255, null=True, verbose_name='中心坐标')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否有效')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '餐馆',
                'verbose_name_plural': '餐馆',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['id'], 'verbose_name': '企业', 'verbose_name_plural': '企业'},
        ),
        migrations.AddField(
            model_name='company',
            name='center',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='中心坐标'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('marked_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='标价')),
                ('payed_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='单价')),
                ('payed_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='小计')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否有效')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx.Dish', verbose_name='产品')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx.Restaurant', verbose_name='餐馆'),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx.Restaurant', verbose_name='餐馆'),
        ),
        migrations.AddField(
            model_name='company',
            name='restaurant',
            field=models.ManyToManyField(blank=True, to='wx.Restaurant', verbose_name='可见餐馆'),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx.Restaurant', verbose_name='餐馆'),
        ),
    ]
