# Generated by Django 2.2 on 2020-02-22 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0003_auto_20200221_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['id'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id'], 'verbose_name': '订单明细', 'verbose_name_plural': '订单明细'},
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='is_available',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_available',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='is_available',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='is_available',
        ),
        migrations.AddField(
            model_name='company',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_confirmed_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人员'),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人员'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='有效'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='已审核'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='已经提交'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_confirmed_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人员'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='contact_mobile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='联系方式'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人员'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='有效'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='已审核'),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='current_role',
            field=models.IntegerField(choices=[(0, '游客'), (1, '客户'), (2, '商家')], default=0, null=True, verbose_name='当前用户角色'),
        ),
        migrations.AlterField(
            model_name='company',
            name='restaurant',
            field=models.ManyToManyField(blank=True, related_name='company_related_restaurant', to='wx.Restaurant', verbose_name='可见餐馆'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_price',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=9, null=True, verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx.Dish', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='餐馆识别码'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wx_user', to='wx.Company', verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='is_client',
            field=models.BooleanField(default=True, verbose_name='是客户'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='是管理员'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='是商家'),
        ),
        migrations.CreateModel(
            name='CompanyEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='姓名')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='已审核')),
                ('is_active', models.BooleanField(default=False, verbose_name='有效')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx.Company', verbose_name='公司')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_employee_confirmed_by', to=settings.AUTH_USER_MODEL, verbose_name='审核人员')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_employee_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人员')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_employee_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '公司员工名单',
                'verbose_name_plural': '公司员工名单',
                'ordering': ['id'],
                'unique_together': {('company', 'employee_name', 'mobile')},
            },
        ),
    ]
