# Generated by Django 2.2 on 2020-02-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0003_auto_20200225_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxuser',
            name='mobile',
            field=models.BinaryField(blank=True, null=True, unique=True, verbose_name='手机号'),
        ),
    ]
