# Generated by Django 2.2 on 2020-02-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0004_auto_20200225_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='手机号'),
        ),
    ]
