# Generated by Django 2.2 on 2020-02-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0004_auto_20200222_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='dish_image_0',
            new_name='dish_image0',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='dish_image_1',
            new_name='dish_image1',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='dish_image_2',
            new_name='dish_image2',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='dish_image_3',
            new_name='dish_image3',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, help_text='企业名称', max_length=255, null=True, unique=True, verbose_name='企业名称'),
        ),
    ]
