# Generated by Django 2.2 on 2020-02-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0005_auto_20200225_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyemployee',
            name='employee_code',
            field=models.CharField(help_text='编号', max_length=200, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterUniqueTogether(
            name='companyemployee',
            unique_together={('company', 'employee_name', 'employee_code')},
        ),
    ]
