# Generated by Django 2.2 on 2020-02-22 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0006_auto_20200222_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='dish_image',
            new_name='dish_image_0',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='dish_image_a',
            new_name='dish_image_1',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='dish_image_b',
            new_name='dish_image_2',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='dish_image_c',
            new_name='dish_image_3',
        ),
    ]
