# Generated by Django 2.2 on 2020-02-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0006_auto_20200225_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyemployee',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='wxuser',
            name='mobile',
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='mobile_data',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='手机号-数据'),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='mobile_index',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='手机号-索引'),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='mobile_data',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='手机号-数据'),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='mobile_index',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='手机号-索引'),
        ),
    ]
