# Generated by Django 2.2 on 2020-02-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0007_auto_20200226_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployee',
            name='mobile_index',
            field=models.TextField(blank=True, max_length=2000, null=True, unique=True, verbose_name='手机号-索引'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='mobile_index',
            field=models.TextField(blank=True, max_length=2000, null=True, unique=True, verbose_name='手机号-索引'),
        ),
    ]
