# Generated by Django 2.2 on 2020-02-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0007_auto_20200222_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='deliver_time_0',
            field=models.TimeField(blank=True, default='8:00:00', help_text='早餐送餐时间', null=True, verbose_name='早餐送餐时间'),
        ),
        migrations.AddField(
            model_name='company',
            name='deliver_time_1',
            field=models.TimeField(blank=True, help_text='午餐送餐时间', null=True, verbose_name='午餐送餐时间'),
        ),
        migrations.AddField(
            model_name='company',
            name='deliver_time_2',
            field=models.TimeField(blank=True, help_text='下午茶送餐时间', null=True, verbose_name='下午茶送餐时间'),
        ),
        migrations.AddField(
            model_name='company',
            name='deliver_time_3',
            field=models.TimeField(blank=True, help_text='晚餐送餐时间', null=True, verbose_name='晚餐送餐时间'),
        ),
        migrations.AddField(
            model_name='company',
            name='deliver_time_4',
            field=models.TimeField(blank=True, help_text='夜宵送餐时间', null=True, verbose_name='夜宵送餐时间'),
        ),
    ]
