# Generated by Django 2.2 on 2020-02-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0008_auto_20200226_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_rated',
            field=models.BooleanField(default=True, help_text='已经点评', verbose_name='已经点评'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rate_notes',
            field=models.TextField(blank=True, help_text='点评', null=True, verbose_name='点评'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rate_score',
            field=models.IntegerField(blank=True, help_text='评分', null=True, verbose_name='评分'),
        ),
    ]
