# Generated by Django 2.2 on 2020-02-23 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0008_auto_20200223_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_time',
            field=models.TimeField(blank=True, help_text='送餐时间', null=True, verbose_name='送餐时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(choices=[(0, '早餐'), (1, '午餐'), (2, '下午茶'), (3, '晚餐'), (4, '夜宵'), (5, '其他')], default=1, help_text='订餐类型 (0-->早餐, 1-->午餐, 2-->下午茶, 3-->晚餐, 4-->夜宵, 5-->其他)', null=True, verbose_name='订餐类型'),
        ),
        migrations.AlterField(
            model_name='chinadistrict',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='chinadistrict',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='company',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='company',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='company',
            name='deliver_time_0',
            field=models.TimeField(default='8:00:00', help_text='早餐送餐时间', null=True, verbose_name='早餐送餐时间'),
        ),
        migrations.AlterField(
            model_name='company',
            name='deliver_time_1',
            field=models.TimeField(default='11:50:00', help_text='午餐送餐时间', null=True, verbose_name='午餐送餐时间'),
        ),
        migrations.AlterField(
            model_name='company',
            name='deliver_time_2',
            field=models.TimeField(default='15:00:00', help_text='下午茶送餐时间', null=True, verbose_name='下午茶送餐时间'),
        ),
        migrations.AlterField(
            model_name='company',
            name='deliver_time_3',
            field=models.TimeField(default='17:50:00', help_text='晚餐送餐时间', null=True, verbose_name='晚餐送餐时间'),
        ),
        migrations.AlterField(
            model_name='company',
            name='deliver_time_4',
            field=models.TimeField(default='20:00:00', help_text='夜宵送餐时间', null=True, verbose_name='夜宵送餐时间'),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='districtlevel',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='districtlevel',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.CreateModel(
            name='DishTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, help_text='标签', max_length=255, null=True, unique=True, verbose_name='标签')),
                ('is_confirmed', models.BooleanField(default=True, help_text='已审核', verbose_name='已审核')),
                ('is_active', models.BooleanField(default=True, help_text='是否有效', verbose_name='是否有效')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='审核人员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_tag_confirmed_by', to=settings.AUTH_USER_MODEL, verbose_name='审核人员')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_tag_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人员')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_tag',
            field=models.ManyToManyField(blank=True, help_text='标签', to='wx.DishTag', verbose_name='标签'),
        ),
    ]
