# Generated by Django 2.2 on 2020-02-23 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0009_auto_20200223_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyemployee',
            options={'ordering': ['id'], 'verbose_name': '企业员工名单', 'verbose_name_plural': '企业员工名单'},
        ),
        migrations.AddField(
            model_name='company',
            name='contact_mobile',
            field=models.CharField(help_text='联系方式', max_length=255, null=True, verbose_name='联系方式'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_person',
            field=models.CharField(help_text='联系人', max_length=255, null=True, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='chinadistrict',
            name='name',
            field=models.CharField(help_text='辖区名称', max_length=100, null=True, verbose_name='辖区名称'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.TextField(help_text='企业地址', max_length=2000, null=True, verbose_name='企业地址'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(help_text='企业名称', max_length=255, null=True, unique=True, verbose_name='企业名称'),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='company',
            field=models.ForeignKey(help_text='企业', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx.Company', verbose_name='企业'),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='employee_name',
            field=models.CharField(help_text='姓名', max_length=200, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='mobile',
            field=models.CharField(help_text='手机号', max_length=20, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_name',
            field=models.CharField(help_text='商品名称', max_length=255, null=True, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(help_text='餐馆', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx.Restaurant', verbose_name='餐馆'),
        ),
        migrations.AlterField(
            model_name='dishtag',
            name='tag_name',
            field=models.CharField(help_text='标签', max_length=255, null=True, unique=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='districtlevel',
            name='level',
            field=models.CharField(help_text='辖区等级', max_length=100, null=True, unique=True, verbose_name='辖区等级'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(help_text='用户', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(help_text='订单日期', null=True, verbose_name='订单日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(help_text='餐馆', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx.Restaurant', verbose_name='餐馆'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='dish',
            field=models.ForeignKey(help_text='商品', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx.Dish', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_count',
            field=models.IntegerField(default=1, help_text='数量', null=True, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='订单', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx.Order', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='contact_mobile',
            field=models.CharField(help_text='联系方式', max_length=255, null=True, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='contact_person',
            field=models.CharField(help_text='联系人', max_length=255, null=True, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_address',
            field=models.TextField(help_text='餐馆地址', max_length=2000, null=True, verbose_name='餐馆地址'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_name',
            field=models.CharField(help_text='餐馆名称', max_length=255, null=True, unique=True, verbose_name='餐馆名称'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='company',
            field=models.ForeignKey(blank=True, help_text='企业', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wx_user', to='wx.Company', verbose_name='企业'),
        ),
    ]
