# Generated by Django 2.2 on 2020-02-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0009_auto_20200226_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(help_text='主照片', null=True, upload_to='dish/', verbose_name='主照片'),
        ),
    ]
