# Generated by Django 2.2 on 2020-02-23 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0010_auto_20200223_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, help_text='审核人员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_confirmed_by', to=settings.AUTH_USER_MODEL, verbose_name='审核人员'),
        ),
        migrations.AddField(
            model_name='dish',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='创建人员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人员'),
        ),
    ]
